site_name: GigaWiki
site_url: https://wiki.gigacafe.org
site_author: 轼水桥头
site_description: 国外黑客松参赛指南
site_favicon: /assets/images/favicon.ico
site_include_search: true
site_include_search_page: true

# Theme configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

# Other configuration options
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
